- name: Validate and reload Caddy
  become: true
  block:
    - name: Validate Caddy config
      ansible.builtin.command: "caddy validate --config {{ caddy_mainfile }}"
      changed_when: false

    - name: Reload Caddy
      ansible.builtin.systemd:
        name: caddy
        state: reloaded