- name: Setup konfwg tool environment
  hosts: local
  become: true

  vars:
    konfwg_cli_path: /usr/local/bin # holds konfwg cli command that runs the tool
    konfwg_code_path: /opt/konfwg # konfwg code
    konfwg_etc_path: /etc/konfwg # konfwg secrets
    konfwg_db_path: /var/lib/konfwg # konfwg database
    konfwg_log_path: /var/log/konfwg # konfwg logs
    konfwg_tmp_path: /tmp/konfwg # konfwg temporary files (CURRENTLY UNIMPLEMENTED)
    konfwg_sudo_path: /etc/sudoers.d # konfwg sudoers configuration
    wg_directory: /etc/wireguard # wireguard directory

  tasks:
    - name: Create konfwg user
      ansible.builtin.user:
        name: konfwg
        system: true
        home: "{{ konfwg_db_path }}"
        shell: /usr/sbin/nologin
        create_home: true
    
    - name: Create konfwg directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ konfwg_code_path }}", owner: root, group: root, mode: "0755" }
        - { path: "{{ konfwg_etc_path }}", owner: root, group: root, mode: "0700" }
        - { path: "{{ konfwg_db_path }}", owner: konfwg, group: konfwg, mode: "0750" }
        - { path: "{{ konfwg_log_path }}", owner: konfwg, group: konfwg, mode: "0750" }

    - name: Configure konfwg sudo permissions
      ansible.builtin.copy:
        dest: "{{ konfwg_sudo_path }}/konfwg"
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -cf %s
        content: |
          Cmnd_Alias KONFWG = \
            /usr/bin/wg, \
            /usr/bin/wg-quick, \
            /bin/systemctl restart wg-quick@wg0

          konfwg ALL=(root) NOPASSWD: KONFWG