- name: Setup WireGuard server
  hosts: local
  become: true

  vars:
    wg_interface: wg0
    wg_directory: /etc/wireguard
    wg_port: 51820
    wg_address_cidr: "10.8.0.1/24"
    wg_out_interface: "eth0"

  tasks:
    - name: Ensure /etc/wireguard
      ansible.builtin.file:
        path: "{{ wg_directory }}"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Check if private key file exists
      ansible.builtin.stat:
        path: "{{ wg_directory }}/{{ wg_interface }}.key"
      register: wg_private_key_stat

    - name: Read private key if file exists
      ansible.builtin.slurp:
        src: "{{ wg_directory }}/{{ wg_interface }}.key"
      register: wg_private_key_slurp
      when: wg_private_key_stat.stat.exists

    - name: Decode private key if exists
      ansible.builtin.set_fact:
        wg_private_key: "{{ wg_private_key_slurp.content | b64decode }}"
      when: wg_private_key_stat.stat.exists

    # COMMENT 1.0: Based on assumption that the private key is 32 (44 char) byte length base64 string ending with '='
    - name: Validate existing private key
      ansible.builtin.set_fact:
        wg_private_key_valid: "{{ (wg_private_key | length > 0) and (wg_private_key is match('^[A-Za-z0-9+/]{43}=$')) }}"
      when: wg_private_key_stat.stat.exists

    - name: Generate server private key if missing or invalid
      ansible.builtin.command: wg genkey
      register: wg_private_key
      changed_when: true
      when: (not wg_private_key_stat.stat.exists) or (wg_private_key_valid is defined and not wg_private_key_valid)

    - name: Save private key to file
      ansible.builtin.copy:
        dest: "{{ wg_directory }}/{{ wg_interface }}.key"
        content: "{{ wg_private_key.stdout }}\n"
        owner: root
        group: root
        mode: "0600"
      when:
        - (not wg_private_key_stat.stat.exists) or (wg_private_key_valid is defined and not wg_private_key_valid)
        - wg_private_key is defined
        - wg_private_key.stdout is defined
        - wg_private_key.stdout | length > 0
      no_log: true

    # COMMENT 1.0: I don't like that these two tasks are repetitive
    - name: Read private key
      ansible.builtin.slurp:
        src: "{{ wg_directory }}/{{ wg_interface }}.key"
      register: wg_private_key_slurp

    - name: Decode private key
      ansible.builtin.set_fact:
        wg_private_key: "{{ wg_private_key_slurp.content | b64decode }}"
    
    - name: Generate server public key
      ansible.builtin.command: "wg pubkey"
      register: wg_public_key
      args:
        stdin: "{{ wg_private_key }}"

    - name: Save server public key
      ansible.builtin.copy:
        dest: "{{ wg_directory }}/{{ wg_interface }}.pub"
        content: "{{ wg_public_key.stdout }}\n"
        owner: root
        group: root
        mode: "0644"
      when: wg_public_key.stdout | length > 0
      no_log: true

    - name: Render WireGuard config
      ansible.builtin.template:
        src: wg0.conf.j2
        dest: "{{ wg_directory }}/{{ wg_interface }}.conf"
        owner: root
        group: root
        mode: "0600"
      notify: Restart wireguard

    - name: Enable and start WireGuard
      ansible.builtin.systemd:
        name: "wg-quick@{{ wg_interface }}"
        enabled: true
        state: started

  handlers:
    - name: Restart wireguard
      ansible.builtin.systemd:
        name: "wg-quick@{{ wg_interface }}"
        state: restarted